[theme]
base = "dark"
primaryColor = "#7C3AED"
backgroundColor = "#030712"
secondaryBackgroundColor = "#0F172A"
textColor = "#FFFFFF"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
